github: [GitHub](https://github.com/Emperor-1231)
twitter: [Twitter](https://x.com/Emperor_1_?s=08)
replit: [Replit](https://replit.com/@AbdoAkojdad)
instagram: [Instagram](https://www.instagram.com/emperor_._1?igsh=enM4aG55Nmwwdmx2)
linkedin: [LinkedIn](https://www.linkedin.com/in/abdo-akojdad-71176a318)
gmail: [Gmail](mailto:abdoakojdad@gmail.com)